const mongoose = require("mongoose");
const dotenv = require("dotenv");

const Food = require("../models/Food");
const Exercise = require("../models/Exercise");

dotenv.config();

const defaultFoods = [
  {
    name: "Cooked White Rice",
    category: "carbohydrate",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatsPer100g: 0.3,
    fiberPer100g: 0.4,
    sugarPer100g: 0.1,
    sodiumPer100g: 1,
    servingUnits: [
      { unit: "cup", gramEquivalent: 158, label: "1 cup cooked rice" },
      { unit: "half_cup", gramEquivalent: 79, label: "1/2 cup cooked rice" },
      { unit: "plate", gramEquivalent: 250, label: "1 medium plate rice" },
    ],
    notes: "Common Bangladesh meal carb source.",
  },
  {
    name: "Small Roti",
    category: "carbohydrate",
    caloriesPer100g: 297,
    proteinPer100g: 8.5,
    carbsPer100g: 56,
    fatsPer100g: 4,
    fiberPer100g: 7,
    sugarPer100g: 1,
    sodiumPer100g: 300,
    servingUnits: [
      { unit: "piece", gramEquivalent: 40, label: "1 small roti" },
      { unit: "piece", gramEquivalent: 60, label: "1 medium roti" },
    ],
    notes: "Use 1-2 small roti depending on meal target.",
  },
  {
    name: "Oats",
    category: "carbohydrate",
    caloriesPer100g: 389,
    proteinPer100g: 16.9,
    carbsPer100g: 66.3,
    fatsPer100g: 6.9,
    fiberPer100g: 10.6,
    sugarPer100g: 0.9,
    sodiumPer100g: 2,
    servingUnits: [
      { unit: "g", gramEquivalent: 1, label: "1 g oats" },
      { unit: "serving", gramEquivalent: 50, label: "50 g oats" },
      { unit: "serving", gramEquivalent: 40, label: "40 g oats" },
    ],
    notes: "Good breakfast carb with fiber.",
  },
  {
    name: "Banana",
    category: "fruit",
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatsPer100g: 0.3,
    fiberPer100g: 2.6,
    sugarPer100g: 12.2,
    sodiumPer100g: 1,
    servingUnits: [
      { unit: "piece", gramEquivalent: 118, label: "1 medium banana" },
      { unit: "piece", gramEquivalent: 90, label: "1 small banana" },
    ],
    notes: "Useful light pre-workout option.",
  },
  {
    name: "Whole Egg",
    category: "protein",
    caloriesPer100g: 143,
    proteinPer100g: 12.6,
    carbsPer100g: 0.7,
    fatsPer100g: 9.5,
    fiberPer100g: 0,
    sugarPer100g: 0.4,
    sodiumPer100g: 142,
    servingUnits: [
      { unit: "piece", gramEquivalent: 50, label: "1 whole egg" },
      { unit: "piece", gramEquivalent: 100, label: "2 whole eggs" },
    ],
    notes: "Affordable protein and fat source.",
  },
  {
    name: "Egg White",
    category: "protein",
    caloriesPer100g: 52,
    proteinPer100g: 10.9,
    carbsPer100g: 0.7,
    fatsPer100g: 0.2,
    fiberPer100g: 0,
    sugarPer100g: 0.7,
    sodiumPer100g: 166,
    servingUnits: [
      { unit: "piece", gramEquivalent: 33, label: "1 egg white" },
      { unit: "piece", gramEquivalent: 66, label: "2 egg whites" },
    ],
    notes: "Adds protein without much fat.",
  },
  {
    name: "Cooked Chicken Breast",
    category: "protein",
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatsPer100g: 3.6,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 74,
    servingUnits: [
      { unit: "g", gramEquivalent: 1, label: "1 g cooked chicken" },
      { unit: "serving", gramEquivalent: 150, label: "150 g cooked chicken" },
      { unit: "serving", gramEquivalent: 180, label: "180 g cooked chicken" },
      { unit: "serving", gramEquivalent: 200, label: "200 g cooked chicken" },
    ],
    notes: "Best affordable high-protein option. Avoid deep frying.",
  },
  {
    name: "Cooked Fish",
    category: "protein",
    caloriesPer100g: 130,
    proteinPer100g: 24,
    carbsPer100g: 0,
    fatsPer100g: 3.5,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 70,
    servingUnits: [
      { unit: "g", gramEquivalent: 1, label: "1 g cooked fish" },
      { unit: "serving", gramEquivalent: 150, label: "150 g cooked fish" },
      { unit: "serving", gramEquivalent: 180, label: "180 g cooked fish" },
      { unit: "serving", gramEquivalent: 200, label: "200 g cooked fish" },
    ],
    notes: "Use rui, pangas, tilapia, tuna, or local affordable fish.",
  },
  {
    name: "Cooked Dal",
    category: "protein",
    caloriesPer100g: 116,
    proteinPer100g: 9,
    carbsPer100g: 20,
    fatsPer100g: 0.4,
    fiberPer100g: 7.9,
    sugarPer100g: 1.8,
    sodiumPer100g: 2,
    servingUnits: [
      { unit: "cup", gramEquivalent: 198, label: "1 cup cooked dal" },
      { unit: "half_cup", gramEquivalent: 99, label: "1/2 cup cooked dal" },
    ],
    notes: "Good protein and fiber source, but also contains carbs.",
  },
  {
    name: "Tok Doi Unsweetened Yogurt",
    category: "dairy",
    caloriesPer100g: 61,
    proteinPer100g: 3.5,
    carbsPer100g: 4.7,
    fatsPer100g: 3.3,
    fiberPer100g: 0,
    sugarPer100g: 4.7,
    sodiumPer100g: 46,
    servingUnits: [
      { unit: "g", gramEquivalent: 1, label: "1 g tok doi" },
      { unit: "serving", gramEquivalent: 100, label: "100 g tok doi" },
      { unit: "serving", gramEquivalent: 200, label: "200 g tok doi" },
    ],
    notes: "Useful snack for satiety.",
  },
  {
    name: "Cooked Chola Chickpeas",
    category: "snack",
    caloriesPer100g: 164,
    proteinPer100g: 8.9,
    carbsPer100g: 27.4,
    fatsPer100g: 2.6,
    fiberPer100g: 7.6,
    sugarPer100g: 4.8,
    sodiumPer100g: 7,
    servingUnits: [
      { unit: "cup", gramEquivalent: 164, label: "1 cup cooked chola" },
      { unit: "half_cup", gramEquivalent: 82, label: "1/2 cup cooked chola" },
    ],
    notes: "Good snack, but portion control is important.",
  },
  {
    name: "Mixed Vegetables",
    category: "vegetable",
    caloriesPer100g: 45,
    proteinPer100g: 2,
    carbsPer100g: 9,
    fatsPer100g: 0.3,
    fiberPer100g: 3.5,
    sugarPer100g: 3,
    sodiumPer100g: 35,
    servingUnits: [
      { unit: "cup", gramEquivalent: 150, label: "1 cup cooked vegetables" },
      { unit: "fist", gramEquivalent: 100, label: "1 fist vegetables" },
      { unit: "serving", gramEquivalent: 200, label: "large vegetable serving" },
    ],
    notes: "Use lau, shak, beans, cabbage, cauliflower, cucumber, salad.",
  },
  {
    name: "Cucumber",
    category: "vegetable",
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatsPer100g: 0.1,
    fiberPer100g: 0.5,
    sugarPer100g: 1.7,
    sodiumPer100g: 2,
    servingUnits: [
      { unit: "piece", gramEquivalent: 200, label: "1 medium cucumber" },
      { unit: "serving", gramEquivalent: 100, label: "100 g cucumber" },
    ],
    notes: "Low-calorie snack.",
  },
  {
    name: "Carrot",
    category: "vegetable",
    caloriesPer100g: 41,
    proteinPer100g: 0.9,
    carbsPer100g: 9.6,
    fatsPer100g: 0.2,
    fiberPer100g: 2.8,
    sugarPer100g: 4.7,
    sodiumPer100g: 69,
    servingUnits: [
      { unit: "piece", gramEquivalent: 60, label: "1 medium carrot" },
      { unit: "serving", gramEquivalent: 100, label: "100 g carrot" },
    ],
    notes: "Useful job-time snack.",
  },
  {
    name: "Milk",
    category: "dairy",
    caloriesPer100g: 60,
    proteinPer100g: 3.2,
    carbsPer100g: 4.8,
    fatsPer100g: 3.3,
    fiberPer100g: 0,
    sugarPer100g: 5,
    sodiumPer100g: 43,
    servingUnits: [
      { unit: "ml", gramEquivalent: 1, label: "1 ml milk" },
      { unit: "cup", gramEquivalent: 244, label: "1 cup milk" },
    ],
    notes: "Can be used with oats.",
  },
  {
    name: "Whey Protein",
    category: "supplement",
    caloriesPer100g: 400,
    proteinPer100g: 80,
    carbsPer100g: 8,
    fatsPer100g: 6,
    fiberPer100g: 0,
    sugarPer100g: 5,
    sodiumPer100g: 300,
    servingUnits: [
      { unit: "scoop", gramEquivalent: 30, label: "1 scoop whey protein" },
    ],
    notes: "Optional only if protein target is hard to reach from food.",
  },
  {
    name: "Black Coffee Unsweetened",
    category: "drink",
    caloriesPer100g: 2,
    proteinPer100g: 0.1,
    carbsPer100g: 0,
    fatsPer100g: 0,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 2,
    servingUnits: [
      { unit: "cup", gramEquivalent: 240, label: "1 cup black coffee" },
    ],
    notes: "Useful pre-workout. Avoid after 5 PM.",
  },
  {
    name: "Tea Without Sugar",
    category: "drink",
    caloriesPer100g: 1,
    proteinPer100g: 0,
    carbsPer100g: 0,
    fatsPer100g: 0,
    fiberPer100g: 0,
    sugarPer100g: 0,
    sodiumPer100g: 1,
    servingUnits: [
      { unit: "cup", gramEquivalent: 240, label: "1 cup tea without sugar" },
    ],
    notes: "Avoid adding sugar during fat-loss phase.",
  },
  {
    name: "Isabgol Husk",
    category: "supplement",
    caloriesPer100g: 200,
    proteinPer100g: 1,
    carbsPer100g: 85,
    fatsPer100g: 0.5,
    fiberPer100g: 80,
    sugarPer100g: 0,
    sodiumPer100g: 10,
    servingUnits: [
      { unit: "tsp", gramEquivalent: 5, label: "1 teaspoon isabgol" },
    ],
    notes: "Optional fiber support. Keep gap from medicines.",
  },
  {
    name: "Tokma Seeds",
    category: "supplement",
    caloriesPer100g: 442,
    proteinPer100g: 14,
    carbsPer100g: 63,
    fatsPer100g: 13,
    fiberPer100g: 34,
    sugarPer100g: 0,
    sodiumPer100g: 20,
    servingUnits: [
      { unit: "tsp", gramEquivalent: 5, label: "1 teaspoon tokma seeds" },
    ],
    notes: "Optional fullness support. Does not magically burn fat.",
  },
];

const defaultExercises = [
  {
    name: "Machine Chest Press",
    category: "strength",
    muscleGroup: "chest",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Sit with back supported.",
      "Keep shoulder blades back.",
      "Press forward with control.",
      "Stop before shoulder discomfort.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Incline Dumbbell Press",
    category: "strength",
    muscleGroup: "chest",
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: [
      "Use light to moderate dumbbells.",
      "Keep shoulder blades back.",
      "Lower slowly and press up.",
    ],
    defaultSets: 3,
    defaultReps: 8,
    defaultRestTime: 90,
  },
  {
    name: "Seated Shoulder Press Machine",
    category: "strength",
    muscleGroup: "shoulders",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Sit tall with back supported.",
      "Do not arch lower back.",
      "Press overhead with control.",
    ],
    defaultSets: 2,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Cable Fly",
    category: "strength",
    muscleGroup: "chest",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Use light weight.",
      "Move slowly through a comfortable range.",
      "Squeeze chest at the front.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Pec Deck",
    category: "strength",
    muscleGroup: "chest",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Adjust seat height.",
      "Keep chest lifted.",
      "Move slowly and avoid shoulder pain.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Dumbbell Lateral Raise",
    category: "strength",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Use small dumbbells.",
      "Keep elbows slightly bent.",
      "Raise arms to shoulder height.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Rope Triceps Pushdown",
    category: "strength",
    muscleGroup: "arms",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Keep elbows close.",
      "Extend fully without leaning.",
      "Control the return.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Dead Bug",
    category: "bodyweight",
    muscleGroup: "core",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Lie on your back.",
      "Keep lower back controlled.",
      "Move opposite arm and leg slowly.",
    ],
    defaultSets: 3,
    defaultReps: 8,
    defaultRestTime: 45,
  },
  {
    name: "Plank",
    category: "bodyweight",
    muscleGroup: "core",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Keep body straight.",
      "Brace core.",
      "Stop before lower back drops.",
    ],
    defaultSets: 3,
    defaultReps: 1,
    defaultRestTime: 45,
  },
  {
    name: "Leg Press",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Place feet shoulder-width.",
      "Lower with control.",
      "Do not lock knees.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 120,
  },
  {
    name: "Goblet Squat to Box",
    category: "strength",
    muscleGroup: "legs",
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Hold dumbbell close to chest.",
      "Sit back to a box or bench.",
      "Keep knees tracking with toes.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Seated Leg Curl",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Adjust pad position.",
      "Curl slowly.",
      "Control the negative phase.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 75,
  },
  {
    name: "Lying Leg Curl",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Keep hips down.",
      "Curl smoothly.",
      "Avoid jerking.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 75,
  },
  {
    name: "Hip Thrust Machine",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Pause one second at the top.",
      "Keep ribs down.",
      "Squeeze glutes.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Glute Bridge Machine",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Keep feet stable.",
      "Drive through heels.",
      "Pause at the top.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Leg Extension",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Use light weight.",
      "Extend knees smoothly.",
      "Stop if knee pain appears.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Standing Calf Raise",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Use full range.",
      "Pause briefly at top.",
      "Do not bounce.",
    ],
    defaultSets: 3,
    defaultReps: 15,
    defaultRestTime: 60,
  },
  {
    name: "Pallof Press",
    category: "strength",
    muscleGroup: "core",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Stand sideways to cable.",
      "Press handle forward.",
      "Resist rotation.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 45,
  },
  {
    name: "Lat Pulldown",
    category: "strength",
    muscleGroup: "back",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Pull elbows down.",
      "Avoid swinging.",
      "Control the return.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Seated Cable Row",
    category: "strength",
    muscleGroup: "back",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Keep chest tall.",
      "Pull toward torso.",
      "Squeeze shoulder blades.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Chest Supported Dumbbell Row",
    category: "strength",
    muscleGroup: "back",
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Use bench support.",
      "Pull dumbbells toward ribs.",
      "Keep movement controlled.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 75,
  },
  {
    name: "Face Pull",
    category: "strength",
    muscleGroup: "shoulders",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Pull rope toward face.",
      "Keep elbows high.",
      "Focus on rear delts.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Reverse Pec Deck",
    category: "strength",
    muscleGroup: "shoulders",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Use light weight.",
      "Open arms slowly.",
      "Control rear delt squeeze.",
    ],
    defaultSets: 2,
    defaultReps: 15,
    defaultRestTime: 60,
  },
  {
    name: "Dumbbell Curl",
    category: "strength",
    muscleGroup: "arms",
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Keep elbows still.",
      "Avoid swinging.",
      "Lower slowly.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 60,
  },
  {
    name: "Hammer Curl",
    category: "strength",
    muscleGroup: "arms",
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Use neutral grip.",
      "Keep wrists straight.",
      "Control each rep.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Side Plank",
    category: "bodyweight",
    muscleGroup: "core",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Keep body straight.",
      "Brace core.",
      "Hold without hip dropping.",
    ],
    defaultSets: 3,
    defaultReps: 1,
    defaultRestTime: 45,
  },
  {
    name: "Bird Dog",
    category: "bodyweight",
    muscleGroup: "core",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Keep hips stable.",
      "Extend opposite arm and leg.",
      "Move slowly.",
    ],
    defaultSets: 3,
    defaultReps: 8,
    defaultRestTime: 45,
  },
  {
    name: "Dumbbell Romanian Deadlift",
    category: "strength",
    muscleGroup: "legs",
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: [
      "Hinge at hips.",
      "Keep neutral spine.",
      "Use light to moderate load.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "Low Step Up",
    category: "strength",
    muscleGroup: "legs",
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: [
      "Use low box.",
      "Hold rail if needed.",
      "Step with control.",
    ],
    defaultSets: 2,
    defaultReps: 10,
    defaultRestTime: 75,
  },
  {
    name: "Cable Pull Through",
    category: "strength",
    muscleGroup: "legs",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Hinge at hips.",
      "Keep back neutral.",
      "Squeeze glutes at top.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 75,
  },
  {
    name: "Farmer Walk",
    category: "strength",
    muscleGroup: "full_body",
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: [
      "Hold moderate dumbbells.",
      "Walk tall.",
      "Brace core and keep posture.",
    ],
    defaultSets: 3,
    defaultReps: 1,
    defaultRestTime: 60,
  },
  {
    name: "Hack Squat",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "intermediate",
    instructions: [
      "Use controlled depth.",
      "Keep knees aligned.",
      "Avoid max loading in month one.",
    ],
    defaultSets: 3,
    defaultReps: 8,
    defaultRestTime: 120,
  },
  {
    name: "Smith Box Squat",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "intermediate",
    instructions: [
      "Sit back to box.",
      "Keep control.",
      "Use safe moderate weight.",
    ],
    defaultSets: 3,
    defaultReps: 8,
    defaultRestTime: 120,
  },
  {
    name: "Supported Split Squat",
    category: "strength",
    muscleGroup: "legs",
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: [
      "Hold rail or support.",
      "Use short comfortable range.",
      "Skip if knee pain appears.",
    ],
    defaultSets: 2,
    defaultReps: 8,
    defaultRestTime: 90,
  },
  {
    name: "Hip Abduction Machine",
    category: "strength",
    muscleGroup: "legs",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Sit tall.",
      "Open hips with control.",
      "Focus on glute medius.",
    ],
    defaultSets: 2,
    defaultReps: 15,
    defaultRestTime: 60,
  },
  {
    name: "Cable Woodchop",
    category: "strength",
    muscleGroup: "core",
    equipment: "cable",
    difficulty: "beginner",
    instructions: [
      "Rotate with control.",
      "Keep hips stable.",
      "Do not use momentum.",
    ],
    defaultSets: 3,
    defaultReps: 12,
    defaultRestTime: 45,
  },
  {
    name: "Incline Machine Chest Press",
    category: "strength",
    muscleGroup: "chest",
    equipment: "machine",
    difficulty: "beginner",
    instructions: [
      "Set incline position.",
      "Press with control.",
      "Avoid shoulder discomfort.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 90,
  },
  {
    name: "EZ Bar Curl",
    category: "strength",
    muscleGroup: "arms",
    equipment: "barbell",
    difficulty: "beginner",
    instructions: [
      "Grip EZ bar comfortably.",
      "Keep elbows near body.",
      "Avoid swinging.",
    ],
    defaultSets: 2,
    defaultReps: 12,
    defaultRestTime: 60,
  },
  {
    name: "Reverse Crunch",
    category: "bodyweight",
    muscleGroup: "core",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Lie on your back.",
      "Curl hips upward.",
      "Control the lowering phase.",
    ],
    defaultSets: 3,
    defaultReps: 10,
    defaultRestTime: 45,
  },
  {
    name: "Incline Treadmill Walk",
    category: "cardio",
    muscleGroup: "cardio",
    equipment: "cardio_machine",
    difficulty: "beginner",
    instructions: [
      "Use low speed and 4-8% incline.",
      "Avoid holding rails if safe.",
      "Stay at conversational pace.",
    ],
    defaultSets: 0,
    defaultReps: 0,
    defaultRestTime: 0,
  },
  {
    name: "Stationary Bike",
    category: "cardio",
    muscleGroup: "cardio",
    equipment: "cardio_machine",
    difficulty: "beginner",
    instructions: [
      "Use moderate pace.",
      "Keep knees comfortable.",
      "Maintain steady breathing.",
    ],
    defaultSets: 0,
    defaultReps: 0,
    defaultRestTime: 0,
  },
  {
    name: "Elliptical",
    category: "cardio",
    muscleGroup: "cardio",
    equipment: "cardio_machine",
    difficulty: "beginner",
    instructions: [
      "Use low impact rhythm.",
      "Keep posture tall.",
      "Maintain conversational pace.",
    ],
    defaultSets: 0,
    defaultReps: 0,
    defaultRestTime: 0,
  },
  {
    name: "Bike Intervals",
    category: "cardio",
    muscleGroup: "cardio",
    equipment: "cardio_machine",
    difficulty: "intermediate",
    instructions: [
      "Warm up five minutes.",
      "Perform 30 seconds hard and 90 seconds easy.",
      "Cool down four minutes.",
    ],
    defaultSets: 0,
    defaultReps: 0,
    defaultRestTime: 0,
  },
  {
    name: "Easy Walk",
    category: "cardio",
    muscleGroup: "cardio",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Walk at easy to moderate pace.",
      "Can split into two shorter walks.",
      "Keep breathing comfortable.",
    ],
    defaultSets: 0,
    defaultReps: 0,
    defaultRestTime: 0,
  },
  {
    name: "Mobility Routine",
    category: "mobility",
    muscleGroup: "full_body",
    equipment: "none",
    difficulty: "beginner",
    instructions: [
      "Include cat-cow, hip flexor stretch, hamstring stretch, ankle rocks, and chest opener.",
      "Move slowly.",
      "Avoid painful ranges.",
    ],
    defaultSets: 0,
    defaultReps: 0,
    defaultRestTime: 0,
  },
];

const addDefaults = (items) =>
  items.map((item) => ({
    ...item,
    isCustom: false,
    createdBy: null,
  }));

const seedDefaultData = async () => {
  try {
    const mongoUri =
      process.env.MONGO_URI ||
      process.env.MONGODB_URI ||
      process.env.DATABASE_URL ||
      process.env.DB_URL;

    if (!mongoUri) {
      throw new Error("MongoDB connection string is missing in .env");
    }

    await mongoose.connect(mongoUri);

    console.log("MongoDB connected for default seed");

    const foods = addDefaults(defaultFoods);
    const exercises = addDefaults(defaultExercises);

    const foodOps = foods.map((food) => ({
      updateOne: {
        filter: {
          name: food.name,
          isCustom: false,
        },
        update: {
          $set: food,
        },
        upsert: true,
      },
    }));

    const exerciseOps = exercises.map((exercise) => ({
      updateOne: {
        filter: {
          name: exercise.name,
          isCustom: false,
        },
        update: {
          $set: exercise,
        },
        upsert: true,
      },
    }));

    if (foodOps.length > 0) {
      await Food.bulkWrite(foodOps);
    }

    if (exerciseOps.length > 0) {
      await Exercise.bulkWrite(exerciseOps);
    }

    console.log(`Default foods seeded: ${foods.length}`);
    console.log(`Default exercises seeded: ${exercises.length}`);

    await mongoose.disconnect();

    console.log("Default seed completed");
    process.exit(0);
  } catch (error) {
    console.error("Default seed failed:", error);
    await mongoose.disconnect();
    process.exit(1);
  }
};

seedDefaultData();